version: "3.9"

services:
  kong:
    image: kong:3.8
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    volumes:
      - ./kong/kong.yml:/kong/declarative/kong.yml:ro
    ports:
      - "8000:8000"
      - "8001:8001"
    networks:
      - kong-net

  auth:
    build: ./services/auth
    volumes:
      - ./services/auth/cmd:/app/cmd
      - ./services/auth/internal:/app/internal
      - ./services/auth/bootstrap:/app/bootstrap
      - ./services/auth/migrations:/app/migrations
      - ./services/auth/go.mod:/app/go.mod
      - ./services/auth/go.sum:/app/go.sum
    env_file:
      - ./services/auth/.env
    command: ["air"]
    networks:
      - kong-net

networks:
  kong-net:
    driver: bridge
