version: "3.9"

services:
  frontend:
    container_name:
         frontend
    build:
      context: ./services/frontend
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./services/frontend:/app
      - /app/node_modules
    networks:
      - shared-net
    restart: unless-stopped

  auth:
    build: ./services/auth
    container_name: auth
    volumes:
      - auth_data:/var/lib/postgresql/data
      - ./services/auth/cmd:/app/cmd
      - ./services/auth/internal:/app/internal
      - ./services/auth/bootstrap:/app/bootstrap
      - ./services/auth/migrations:/app/migrations
      - ./services/auth/go.mod:/app/go.mod
      - ./services/auth/go.sum:/app/go.sum
    env_file:
      - ./services/auth/.env
    command: ["air"]
    depends_on:
      - auth-db
    restart: unless-stopped
    networks:
      - shared-net

  auth-db:
    image: postgres:17
    container_name: auth-db
    ports:
      - "5432:5432"
    env_file:
      - ./services/auth/.env
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - shared-net

  kong:
    image: kong:3.8
    container_name: kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_PREFIX: /tmp/kong
    volumes:
      - ./kong/kong.yml:/kong/declarative/kong.yml:ro
    ports:
      - "8000:8000"
      - "8001:8001"
    networks:
      - shared-net
    restart: unless-stopped

volumes:
  auth_data:
  auth_db_data:

networks:
  shared-net:
    driver: bridge