services:
  frontend:
    container_name: frontend
    build:
      context: ./services/frontend
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./services/frontend:/app
      - /app/node_modules
    networks:
      - shared-net
    restart: unless-stopped

  auth:
    build: ./services/auth
    container_name: auth
    volumes:
      - auth_data:/var/lib/postgresql/data
      - ./services/auth/cmd:/app/cmd
      - ./services/auth/internal:/app/internal
      - ./services/auth/bootstrap:/app/bootstrap
      - ./services/auth/migrations:/app/migrations
      - ./services/auth/go.mod:/app/go.mod
      - ./services/auth/go.sum:/app/go.sum
    env_file:
      - ./services/auth/.env
    command: ["air"]
    depends_on:
      - auth-db
    restart: unless-stopped
    networks:
      - shared-net

  auth-db:
    image: postgres:17
    container_name: auth-db
    ports:
      - "5432:5432"
    env_file:
      - ./services/auth/.env
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - shared-net

  products:
    build: ./services/products
    container_name: products
    volumes:
      - products_data:/var/lib/postgresql/data
      - ./services/products/internal:/app/internal
      - ./services/products/migrations:/app/migrations
    env_file:
      - ./services/products/.env
    command: [ "air" ]
    depends_on:
      - products-db
    restart: unless-stopped
    networks:
      - shared-net

  products-db:
    image: postgres:17
    container_name: products-db
    ports:
      - "5433:5432"
    env_file:
      - ./services/products/.env
    volumes:
      - products_db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - shared-net

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:8080"
    networks:
      - shared-net
    depends_on:
      - auth
    restart: unless-stopped

volumes:
  auth_data:
  auth_db_data:
  products_data:
  products_db_data:

networks:
  shared-net:
    driver: bridge
